ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/../../..
PROJECT_NAME := {{PROJECT_NAME}}
NPM_WORKSPACE := {{NPM_WORKSPACE}}
PROJECT_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
PROJECT_STACK := node
include $(ROOT)/make/report.mk
include $(ROOT)/make/node.mk
